apiVersion : apps/v1
kind: Deployment
metadata:
  name: django-deployment
  labels:
    app: django-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      project: django-app
  template:
    metadata:
      labels:
        project: django-app # the service looks for pods with this label
    spec:
      containers:
      - name: django-web
        image: web:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 80
          protocol: TCP
        env:
        - name: SECRET_KEY
          value: replace_me
        - name: DEBUG
          value: "False"
        - name: DATABASE_URL
          value: postgres://test_k8s:OwOtBep9Frut@192.168.1.35:5432/test_k8s
        - name: ALLOWED_HOSTS
          value: 127.0.0.1,localhost,172.26.28.91

---
apiVersion: v1
kind: Service
metadata:
  name: django-service
  labels:
    env: prod
    owner: fch
spec:
  selector:
    project: django-app # select pods with this label
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  type: NodePort

