apiVersion: v1
kind: Pod
metadata:
  name: web
  labels:
        env: prod
        app: main
        tier: frontend
        owner: fch
spec:
  containers:
    - name: container-nginx
      image: web:latest
      imagePullPolicy: Never
      ports:
        - containerPort: 80
